# Generated by Django 3.1.1 on 2020-09-27 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del autor', max_length=50)),
                ('apellido', models.CharField(help_text='Apellido del autor', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la editorial', max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Genero al que pertenece', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del lector', max_length=50)),
                ('apellido', models.CharField(help_text='Apellido del lector', max_length=50)),
                ('telefono', models.CharField(help_text='Numero de telefono', max_length=10)),
                ('direccion', models.CharField(help_text='Direccion de donde vive', max_length=127)),
                ('correo', models.EmailField(help_text='Direccion del correo electronico', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Titulo del libro', max_length=150)),
                ('status', models.CharField(blank=True, default='Disponible', help_text='Disponibilidad del libro', max_length=27)),
                ('año', models.CharField(help_text='Introduce el año', max_length=50)),
                ('edicion', models.CharField(max_length=50, verbose_name='Introduce la edicion')),
                ('precio', models.FloatField(verbose_name='Introduce el precio')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.autor')),
                ('editorial_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.editorial')),
                ('genero_Id', models.ManyToManyField(help_text='Seleccione un genero para este libro', to='libreria.Genero')),
            ],
            options={
                'ordering': ['titulo', 'autor'],
            },
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_Alquiler', models.DateField(help_text='Fecha del alquiler')),
                ('fecha_Entrega', models.DateField(help_text='Fecha de cuando termina el alquiler')),
                ('precio', models.FloatField(help_text='Precio del alquiler')),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.lector')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.libro')),
            ],
        ),
    ]
