# Generated by Django 3.1.1 on 2020-09-28 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='editorial_Id',
            new_name='editorial',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='genero_Id',
            new_name='genero',
        ),
    ]
