# Generated by Django 3.1.1 on 2020-09-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='genero_Id',
            field=models.ManyToManyField(help_text='Seleccione un genero para este libro', to='Libreria.Genero'),
        ),
    ]
